# Generated by Django 5.2.6 on 2025-09-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_video_description_post_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Default Light'), ('dark', 'Default Dark'), ('sepia', 'Sepia'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('monochrome', 'Monochrome')], default='light', max_length=10),
        ),
    ]
