# Generated by Django 5.2.6 on 2025-09-13 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_status',
            field=models.CharField(choices=[('needs_review', 'Needs Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved')], default='needs_review', max_length=20),
        ),
        migrations.CreateModel(
            name='PrivateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_feedback', to='blog.post')),
            ],
        ),
    ]
