# Generated by Django 5.2.6 on 2025-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('project', 'Project'), ('showcase', 'Showcase')], default='project', max_length=20),
        ),
    ]
