# Generated by Django 5.2.6 on 2025-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='temp_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
