# Generated by Django 5.2.6 on 2025-09-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_portfolio_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='temp_field',
        ),
    ]
