# Generated by Django 5.2.6 on 2025-09-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_family_profile_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
