# Generated by Django 5.2.6 on 2025-09-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_family_invite_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='annotation',
            new_name='media_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='audio_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_description',
        ),
    ]
