# Generated by Django 5.2.6 on 2025-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_rename_annotation_post_media_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('journal', 'Journal'), ('photo', 'Photo'), ('video', 'Video')], default='journal', max_length=10),
        ),
    ]
