# Generated by Django 5.2.6 on 2025-10-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
