# Generated by Django 5.2.6 on 2025-10-03 05:50

from django.db import migrations, models
from django.utils.text import slugify

def populate_tag_slugs(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    for tag in Tag.objects.all():
        base_slug = slugify(tag.name)
        unique_slug = base_slug
        num = 1
        while Tag.objects.filter(slug=unique_slug).exclude(pk=tag.pk).exists():
            unique_slug = f"{base_slug}-{num}"
            num += 1
        tag.slug = unique_slug
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.RunPython(
            code=populate_tag_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Default Light'), ('dark', 'Default Dark'), ('sepia', 'Sepia'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('monochrome', 'Monochrome'), ('vibrant', 'Vibrant')], default='light', max_length=10),
        ),
    ]
