# Generated by Django 5.2.6 on 2025-10-06 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_tag_slug_alter_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='posts',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PresentationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.presentation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
