# Generated by Django 5.2.6 on 2025-10-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_presentation_posts_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='posts',
            field=models.ManyToManyField(through='blog.PresentationPost', to='blog.post'),
        ),
    ]
