# Generated by Django 5.2.6 on 2025-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_presentation_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Default Light'), ('dark', 'Default Dark'), ('sepia', 'Sepia'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('monochrome', 'Monochrome'), ('vibrant', 'Vibrant'), ('christmas', 'Christmas')], default='light', max_length=10),
        ),
    ]
