# Generated by Django 5.2.6 on 2025-10-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_rubric_level_criterion_assessment_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.rubric'),
        ),
    ]
